# SPDX-License-Identifier: MIT-0 OR Unlicense
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# 
version = 1
SPDX-PackageName = "ism-data"
SPDX-PackageSupplier = "Knitli Inc. <knitli@knitli.com>"
SPDX-PackageDownloadLocation = "https://github.com/marquetools/ism-data"

[[annotations]]
path = [
  "crates/*/README.md",
  "crates/*/Cargo.toml"
  "crates/*/build.rs",
  "crates/*/src/*",
  ".github/**",
  "tools/**",
  "./*"
]
precedence = "closest"
SPDX-License-Identifier = "MIT-0 OR Unlicense"

[[annotations]]
path = [
  "crates/*/data/**"
]
precedence = "closest"
SPDX-FileCopyrightText = "United States Government, Public Domain"
SPDX-License-Identifier = "LicenseRef-PublicDomain"
